export enum NotificationType {
  ROUND_OPENED = 'round_opened',
  CONTRIBUTION_REMINDER = 'contribution_reminder',
  PAYMENT_REMINDER = 'payment_reminder',
  PAYOUT_RECEIVED = 'payout_received',
  MEMBER_JOINED = 'member_joined',
  MEMBER_LEFT = 'member_left',
  MEMBER_REMOVED = 'member_removed',
  SYSTEM_ALERT = 'system_alert',
  KYC_SUBMITTED = 'kyc_submitted',
  ADMIN_TRANSFERRED = 'admin_transferred',
  PENALTY_DISPUTED = 'penalty_disputed',
  PENALTY_RESOLVED = 'penalty_resolved',
  MEMBER_SUSPENDED = 'member_suspended',
  MEMBER_REINSTATED = 'member_reinstated',
  GROUP_ANNOUNCEMENT = 'group_announcement',
  IMPERSONATION_REQUEST = 'impersonation_request',
  WAITLIST_ADMITTED = 'waitlist_admitted',
}
